version: '3'

services:
  discord-bot:
    build: .
    depends_on:
      - mysql
    environment:
      BOT_TOKEN: "⚠️ YOUR_BOT_TOKEN ⚠️"
      WEBHOOK_ID: "⚠️ YOUR_WEBHOOK_ID ⚠️"
      WEBHOOK_URL: "⚠️ YOUR_WEBHOOK_URL ⚠️"
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: VoiceMaster
      DATABASE_USER: VoiceMaster
      DATABASE_PASSWORD: "⚠️ DATABASE_PASSWORD ⚠️"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "⚠️ DATABASE_ROOT_PASSWORD ⚠️"
      MYSQL_DATABASE: "⚠️ DATABASE_NAME ⚠️"
      MYSQL_USER: "⚠️ DATABASE_USER ⚠️"
      MYSQL_PASSWORD: "⚠️ DATABASE_PASSWORD ⚠️"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
