version: '3'

services:
  discord-bot:
    build: .
    container_name: VoiceMaster
    depends_on:
      - mysql
    environment:
      BOT_TOKEN: YOUR_BOT_TOKEN
      WEBHOOK_ID: YOUR_WEBHOOK_ID
      WEBHOOK_URL: YOUR_WEBHOOK_URL
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: YOUR_DATABASE_NAME
      DATABASE_USER: YOUR_DATABASE_USER
      DATABASE_PASSWORD: YOUR_DATABASE_PASSWORD
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD
      MYSQL_DATABASE: YOUR_DATABASE_NAME
      MYSQL_USER: YOUR_DATABASE_USER
      MYSQL_PASSWORD: YOUR_DATABASE_PASSWORD
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '3306:3306'
    networks:
      - app-network

volumes:
  mysql_data:
    
networks:
  app-network:
    driver: bridge